from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

if not GetDepend('USING_BATTERY_CALCULATOR'):
    SrcRemove(src, 'battery_table.c')

path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32_OED_EPD_V11'], CPPPATH = path)

Return('group')
