import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

# Prepare environment.
PrepareEnv()

################################## change rtconfig.xxx to customize build ########################################

# Add bootloader project
AddBootLoader(SIFLI_SDK,rtconfig.CHIP)

# Set default compile options
SifliEnv()

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
   
# Prepare building environment
objs = PrepareBuilding(env)

# Build application.
DoBuilding(TARGET, objs)

# Add flash table
AddFTAB(SIFLI_SDK,rtconfig.CHIP)


# Add existing file system image bin
fs_bin=FileSystemBuild( "../disk", env)
AddCustomImg("fs_root",bin=[fs_bin])


# Add EPD wave form image bin
if GetDepend('EPD_WAVEFORM_USE_BIN'):
    epd_wave_bin="../waveform/epd_waveform.bin"
    AddCustomImg("wave_table",bin=[epd_wave_bin])

# Generate download .bat script
GenDownloadScript(env)
