from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32_OED_EPD_V12'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32_OED_EPD_V12'):
    group = group + SConscript(os.path.join(cwd, '../sf32-oed-epd_base/SConscript'), variant_dir="base", duplicate=0)

Return('group')
